"""
Devnet deployment preparation service.
Since the server has no Rust/Anchor toolchain, this service:
1. Validates the code via AI
2. Generates deploy.sh script
3. Packages everything into a downloadable ZIP (base64)
4. Returns step-by-step deployment instructions
"""

import base64
import io
import zipfile
from typing import Optional

from src.services.validate_service import validate_code
from src.utils.logger import logger


def _generate_deploy_script(program_name: str) -> str:
    """Generate a deploy.sh script for devnet deployment."""
    return f"""#!/bin/bash
# Kazt Forge -- Devnet Deployment Script
# Program: {program_name}
# Generated by kazt.fun

set -e

echo "=== Kazt Forge Devnet Deployer ==="
echo ""

# 1. Check prerequisites
command -v solana >/dev/null 2>&1 || {{ echo "Error: solana CLI not found. Install: https://docs.solanalabs.com/cli/install"; exit 1; }}
command -v anchor >/dev/null 2>&1 || {{ echo "Error: anchor CLI not found. Install: https://www.anchor-lang.com/docs/installation"; exit 1; }}

# 2. Configure for devnet
echo "[1/5] Configuring Solana CLI for devnet..."
solana config set --url devnet

# 3. Check/create keypair
if [ ! -f ~/.config/solana/id.json ]; then
    echo "[2/5] Generating new keypair..."
    solana-keygen new --no-bip39-passphrase -o ~/.config/solana/id.json
else
    echo "[2/5] Using existing keypair"
fi

# 4. Airdrop devnet SOL
echo "[3/5] Requesting devnet SOL airdrop..."
solana airdrop 2 || echo "Airdrop failed -- you may need to wait or use https://faucet.solana.com"

echo "Balance:"
solana balance

# 5. Build
echo "[4/5] Building program..."
anchor build

# 6. Deploy
echo "[5/5] Deploying to devnet..."
anchor deploy --provider.cluster devnet

echo ""
echo "=== Deployment Complete ==="
echo "Program ID:"
solana address -k target/deploy/{program_name}-keypair.json
echo ""
echo "View on Solana Explorer:"
echo "https://explorer.solana.com/address/$(solana address -k target/deploy/{program_name}-keypair.json)?cluster=devnet"
"""


def _generate_readme(program_name: str) -> str:
    """Generate deployment README."""
    return f"""# {program_name} -- Devnet Deployment

Generated by [Kazt Forge](https://kazt.fun)

## Prerequisites

1. **Solana CLI**: https://docs.solanalabs.com/cli/install
2. **Anchor CLI**: https://www.anchor-lang.com/docs/installation
3. **Rust**: https://rustup.rs/

## Quick Deploy

```bash
# Make deploy script executable
chmod +x deploy.sh

# Run deployment
./deploy.sh
```

## Manual Steps

1. Configure Solana for devnet:
   ```bash
   solana config set --url devnet
   ```

2. Get devnet SOL:
   ```bash
   solana airdrop 2
   ```
   Or use the faucet: https://faucet.solana.com

3. Build the program:
   ```bash
   anchor build
   ```

4. Deploy:
   ```bash
   anchor deploy --provider.cluster devnet
   ```

5. Get your Program ID:
   ```bash
   solana address -k target/deploy/{program_name}-keypair.json
   ```

## Notes

- This is a **devnet** deployment (test network, free SOL)
- The program ID will be generated on first deploy
- After deployment, update `declare_id!()` in lib.rs with your actual program ID
- Run tests: `anchor test`

---
Built with Kazt Forge | kazt.fun
"""


async def prepare_devnet_deploy(
    files: list[dict],
    program_name: str,
) -> dict:
    """
    Prepare a devnet deployment package.
    1. Validate code via AI
    2. Generate deploy script
    3. Package as ZIP (base64)
    4. Return instructions
    """
    # 1. Validate
    validation = await validate_code(files)
    build_ok = validation.get("build", {}).get("status") == "pass"
    has_critical = any(
        s.get("severity") == "high" for s in validation.get("security", [])
    )

    if not build_ok:
        return {
            "ready": False,
            "package_b64": "",
            "instructions": [
                "Build validation failed. Fix the errors before deploying.",
                *validation.get("build", {}).get("errors", []),
            ],
            "deploy_script": "",
            "program_name": program_name,
            "validation": validation,
        }

    # 2. Generate scripts
    deploy_script = _generate_deploy_script(program_name)
    readme = _generate_readme(program_name)

    # 3. Create ZIP in memory
    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        # Add all project files
        for f in files:
            zf.writestr(f["path"], f["content"])

        # Add deploy script
        zf.writestr("deploy.sh", deploy_script)

        # Add README
        zf.writestr("DEPLOY_README.md", readme)

    zip_b64 = base64.b64encode(zip_buffer.getvalue()).decode("utf-8")

    # 4. Build instructions
    instructions = [
        "Download and extract the project ZIP",
        "Install prerequisites: Solana CLI, Anchor CLI, Rust",
        "Run: chmod +x deploy.sh && ./deploy.sh",
        "Or manually: solana config set --url devnet",
        "Get devnet SOL: solana airdrop 2",
        "Build: anchor build",
        "Deploy: anchor deploy --provider.cluster devnet",
        "Your Program ID will be shown after deployment",
    ]

    if has_critical:
        instructions.insert(
            0,
            "WARNING: High severity security issues detected. Review before deploying to mainnet."
        )

    logger.info(f"Devnet deploy package prepared: {program_name}, zip_size={len(zip_buffer.getvalue())}")

    return {
        "ready": True,
        "package_b64": zip_b64,
        "instructions": instructions,
        "deploy_script": deploy_script,
        "program_name": program_name,
        "validation": validation,
    }
